apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- migration-job.yaml

images:
- name: gustavokubiack/mail-api
  newName: gustavokubiack/mail-api
  newTag: 89b71c9981bd6e3c33e56eddc40099281e12e3cf
