apiVersion: batch/v1
kind: Job
metadata:
  name: mail-api-migrations
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: gustavokubiack/mail-api
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DEBUG
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_BACKEND
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_HOST
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_PORT
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_HOST_USER
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_HOST_PASSWORD
            - name: EMAIL_USE_TLS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: EMAIL_USE_TLS
            - name: DEFAULT_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DEFAULT_FROM_EMAIL
            - name: DJANGO_SETTINGS_MODULE
              value: app.settings
      restartPolicy: Never
