apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gustavokubiack/mail-front
  newName: gustavokubiack/mail-front
  newTag: 204fe390d3d3cc41cc3bd709816fee0f674f2230
