apiVersion: v1
kind: Service
metadata:
  name: mail-front-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: mail-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
